### PR TITLE
[ISSUE 632] Fast follow for API/Infra issues

### LINKED ISSUE #632: Fast follow for API/Infra issues
### Summary

There will be changes in the infra template and we need to make some fixes to the API infrastructure issues that are occurring. 

### Acceptance Criteria

- [ ] Terratest passing
- [ ]  stable API deployment

### PR DESCRIPTION
**Pull request by daphnegold**
## Summary
Fixes #632 

## Changes proposed
- Hardcode number of Gunicorn workers until we are able to accurately use Fargate vCPU in calculations
- Adjust CPU/Memory to a more reasonable number to handle 2 workers with 4 threads per.

## Context for reviewers
Deploys were unstable, sometimes succeeding and sometimes not, because utilization was maxing out during task startup. This caused the health check to repeatedly fail, and the task to exit. 

```
{"name":"src.logging.config","msg":"start %s: %s %s %s, hostname %s, pid %i, user %i(%s)","args":["src","CPython","3.12.0","Linux","ip-172-31-68-81.ec2.internal",17,1001,"runner"],"levelname":"INFO","levelno":20,"pathname":"/api/src/logging/config.py","filename":"config.py","module":"config","exc_info":null,"exc_text":null,"stack_info":null,"lineno":121,"funcName":"log_program_info","created":1698956338.6875927,"msecs":687.0,"relativeCreated":7214.773893356323,"thread":140649767435136,"threadName":"MainThread","processName":"MainProcess","process":17,"taskName":null,"hostname":"ip-172-31-68-81.ec2.internal","cpu_count":2,"cpu_usable":2,"message":"start src: CPython 3.12.0 Linux, hostname ip-172-31-68-81.ec2.internal, pid 17, user 1001(runner)"}
```
I've found it 🐟 that despite our app being set at 256 (0.25 vCPU), Python was recording 2 usable CPU during startup, and spinning up 4 workers, more than it could handle. Testing revealed that the `cpu_count` and `cpu_usable` is coming from the underlying EC2 instance hosting (hinted at by the internal IP address) our Fargate tasks, which scale depending on the requested allotment for the task but is not equal. If I bumped CPU incrementally to 4096, then we see available CPU jump up from 2-4. Unfortunately, to accurately calculate the number of workers, we need Fargate available CPU not underlying EC2.

I haven't found this documented anywhere explicitly, we just reasoned it out. So, if you have ideas let me know!

We should continue to monitor API health and make adjustments.

## Some suggestions on how we might fix this someday
- Pass CPU value from Terraform config to API as an environment variable
- Fetch task metadata from AWS over the internets and use that (meh)

### CODE REVIEW

**Review by chouinar — APPROVED** [review]
LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

**Comment by daphnegold** [comment]
> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

I really doubt it, but let me know if you take a crack at it. What indicators do you have that `os.sched_getaffinity(0)` would return anything different if we have the logic on which server to start in an app entrypoint rather than in Gunicorn config? Also negatives there are that the app is no longer environment agnostic, and complicates Gunicorn config, probably more.

**Comment by daphnegold** [comment]
> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

I really doubt it, but let me know if you take a crack at it. 

What indicators do you have that `os.sched_getaffinity(0)` would return anything different if we have the logic on which server to start in an app entrypoint rather than in Gunicorn config? The logs above are from when Flask  If the underlying issue is how Fargate reports available CPUs, won't make a difference. Potential negatives: app would no longer environment agnostic, and complicates Gunicorn config, probably more.

> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

I really doubt it, but let me know if you take a crack at it. 

What indicators do you have that `os.sched_getaffinity(0)` would return anything different if we have the logic on which server to start in an app entrypoint rather than in Gunicorn config? If issue is how Fargate reports vCPUs then it'll persist. The log above is from when our app is configuring logging at startup, and it's reported incorrectly there.

**Comment by daphnegold** [comment]
> LGTM! Hopefully tuning these up fixes it - if not we can try setting up gunicorn a bit more directly in the app and see if that fixes it? Wondering if the way it works right now is causing issues

I really doubt it, but let me know if you take a crack at it. 

What indicators do you have that `os.sched_getaffinity(0)` would return anything different if we have the logic on which server to start in an app entrypoint rather than in Gunicorn config? If issue is how Fargate reports vCPUs then it'll persist. The log above is from when our app is configuring logging at startup, and it's reported incorrectly there.

**Pull request merged**
