### PR TITLE
[Issue #2029] Merge Nava fork to HHS

### LINKED ISSUE #229: Deprecated ticket
### Description

### PR DESCRIPTION
**Pull request by acouch**
## Summary
Fixes #229

## Changes proposed
Merge the Nava work during the hiatus over to HHS.

## Additional information
The issue numbers should line up correctly

### CODE REVIEW

**Review by mdragon — DISMISSED** [review]
Signing off in so much as my changes from the fork are faithfully represented here. Maybe try smaller PRs next time *ducks*

**Review by chouinar — DISMISSED** [review]
LGTM - skimmed through the API folder and didn't see anything off

**Comment by andycochran** [comment]
This will be "Rebase and merge" not "Squash and merge" right? ("Create a merge commit" might not be bad either, as it'd be a clear indicator of when this happened.)

**Comment by acouch** [comment]
> This will beRebase and merge

@andycochran , correct

**Review by chouinar — DISMISSED** [review]

**Review by chouinar — APPROVED** [review]

**Pull request merged**
