### PR TITLE
[Unticketed] Upgrade Analytics code to Python 3.13

### PR DESCRIPTION
**Pull request by chouinar**
## Changes proposed
Upgrade Analytics to Python 3.13

## Context for reviewers
The API has already done this upgrade, Python 3.13 has very few impactful changes (mostly experimental features you need to enable). Doing this to try to resolve some build issues I'm seeing in CI/CD, especially regarding the renovate upgrades that are being attempted: https://github.com/HHS/simpler-grants-gov/pull/1994

### CODE REVIEW

**Review by coilysiren — APPROVED** [review]
:thank-you: 🚀

**Comment by coilysiren** [comment]
Oh no it's broken

And it's broken on python 3.13 specially! Wow

**Comment by chouinar** [comment]
Apparently one library that there is a dependency for relies on Python 3.12 and earlier. Yay

**Comment by chouinar** [comment]
Did a very rough upgrade of packages with `poetry update` - won't have changed anything that had more restrictive versioning than just wanting the latest. Had to fix a few other minor things here and there to get everything happy.

Will rely on Renovate to handle any further package upgrades

**Review by coilysiren — APPROVED** [review]

**Pull request merged**
