### PR TITLE
[Issue #1820] Syncs ADRs with wiki

### LINKED ISSUE #1820: Move ADRs into `documentation/wiki/` to sync with public wiki
### Summary

In order to sync the ADRs between the GitHub repo and the wiki, we need to move them into the `documentation/wiki/` sub-directory.

### Acceptance criteria

- [ ] ADRs are now stored in `documentation/wiki/decisions/`
- [ ] New ADRs can be added either through a PR in GitHub or a change request in GitBook

### PR DESCRIPTION
**Pull request by widal001**
## Summary

Moves `documentation/decisions/` to `documentation/wiki/decisions/` so that future ADRs will show up in both GitBook and in the repository.

Fixes #1820 

### Time to review: __5 mins__

- Moves `documentation/decisions/` to `documentation/wiki/decisions/`
- Adds a `adr/README.md` file so that wiki users can browse all of the ADRs
- Renames `infra/index.md` to `infra/README.md` to do the same for Infra ADRs
- Updates `SUMMARY.md` so that the newly synced files will appear in the wiki UI
- Adds `ci-wiki-links.yml` to check that all files in `documentation/wiki/` are in `SUMMARY.md`

**Note:** If ADRs are introduced via a PR in GitHub, they also need to be added to `SUMMARY.md` in order to appear in the wiki. This PR also adds a CI check that will run when the `documentation/wiki/` directory is updated in a PR and it will check that all markdown files are linked in `SUMMARY.md`

Here's an example of what [a failure looks like](https://github.com/HHS/simpler-grants-gov/actions/runs/8852840052/job/24312326722?pr=1826)

To see what this will look like in the wiki, you can [check out this preview](https://wiki.simpler.grants.gov/~/revisions/A6Rq14geLjP7gUi55Fxa/decisions/adr) it should look like this:

Screenshot 2024-04-24 at 5 02 51 PM

### CODE REVIEW

**Review by sumiat — COMMENTED** [review]
PR looks good to me! 
Just to make sure, for the description you stated below, you are adding it to the wiki and it will remain in github? we're not removing it from github?: 
> Moves documentation/decisions/ to documentation/wiki/decisions/

I think we just need a couple follow up things to make sure we're aligned on the process. These do not block approval of the PR: 
> Note: Future ADRs should probably default to being drafted in GitBook. If ADRs are introduced via a PR in GitHub, they also need to be added to SUMMARY.md in order to appear in the wiki.

- That's easy to miss so we'll want to make it clear to the team that we're creating the ADRs in GitBook now. 
- Could you remind me @widal001 how often we're syncing the wiki to github?

**Comment by acouch** [comment]
Didn't know this was possible! Very cool.

> If ADRs are introduced via a PR in GitHub, they also need to be added to SUMMARY.md in order to appear in the wiki.

I would like to check w/ the team about this. The PR process has worked for us so far. We could use [adrlog](https://github.com/HHS/simpler-grants-gov/blob/7a6edeeadd13432450888ad2020ea8b9d735ce01/documentation/decisions/infra/index.md?plain=1#L5) to generate the index so it happens automatically.

**Comment by widal001** [comment]
@sumiat @acouch Wanted to update y'all on some changes I made to this PR and answer some of the questions above:

### Updates

- I added a new CI check that runs when a PR is opened that changes the `documentation/wiki/` directory. It will fail if any of the markdown files that are added to this wiki are missing from the `SUMMARY.md` which is useful outside of just the new ADR workflow since it will also allow us to lint PRs opened by open source contributors that touch the wiki.
- Here's an example of [a failure](https://github.com/HHS/simpler-grants-gov/actions/runs/8852840052/job/24312326722) which lists the missing file and the [source commit in which I removed that file to trigger the failure](https://github.com/HHS/simpler-grants-gov/pull/1826/commits/9d83f2df46c7e4e1bb410a3e5f738d8899726d30)
- Now that we have all of the ADRs added, folks will only need to add individual ADRs to the `SUMMARY.md` file and this check will fail if they forget to do that

### Other notes and responses

> Could you remind me @widal001 how often we're syncing the wiki to github?

The wiki and GitHub get synced every time a new GitBook change request is merged and every time a GitHub PR is merged that contains code which modifies `documentation/wiki/`

> I would like to check w/ the team about this. The PR process has worked for us so far. We could use [adrlog](https://github.com/HHS/simpler-grants-gov/blob/7a6edeeadd13432450888ad2020ea8b9d735ce01/documentation/decisions/infra/index.md?plain=1#L5) to generate the index so it happens automatically.

Even if we use `adrlog` to generate the index, we still need to add new files to `documentation/wiki` for GitBook to pick them up. The CI check that I mentioned above will fail when this doesn't happen so we should be able to catch it in the PR, but we can also explore options for automating the process of inserting new links as well down the line if manually adding them when a new ADR is created becomes burdensome.

**Review by sumiat — DISMISSED** [review]
Thanks for the updates, Billy! LGTM. Not sure if Aaron has more questions!

**Review by sarahknoppA6 — APPROVED** [review]
Wow, this looks great! These changes will be really helpful. Thank you very much for putting them together and for the thorough documentation around them :)

**Review by sumiat — APPROVED** [review]
Approved!

**Pull request merged**
