### PR TITLE
Methods in base.py to pull to and from SQL tables, unit tests in test_base.py and successful code formatting and quality checks

### PR DESCRIPTION
**Pull request by ebuwa-evbuoma-fike**
## Summary
Important Note: Work-in-progress #{1599} 

## Changes proposed

- Create `db.py,`  to establish a connection to the database using a SQLAlchemy engine object.
- Create the to_sql and from_sql  methods in `base.py`.
- Set up database configurations.
- Create and validate unit tests in `test_base.py`.

Screenshot 2024-05-10 at 3 13 32 PM
Screenshot 2024-05-10 at 2 43 31 PM

### CODE REVIEW

**Comment by coilysiren** [comment]
You can convert this to a draft PR if it is still "work in progress" as the description says

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by ebuwa-evbuoma-fike** [comment]
> You can convert this to a draft PR if it is still "work in progress" as the description says
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

@coilysiren can draft PRs be viewed? My goal was to make sure Alex could access this

**Comment by coilysiren** [comment]
@ebuwa-evbuoma-fike 

> can draft PRs be viewed? My goal was to make sure Alex could access this

Yes draft PRs have the same visibility rules as normal PRs

**Comment by acouch** [comment]
The code from this PR was adopted during the break with this PR https://github.com/navapbc/simpler-grants-gov/pull/72

**Pull request closed without merging**
