### PR TITLE
[Issue] #3083 update actions.ts to fix err and val

### LINKED ISSUE #3083: /subscribe page: Fix "Subscribe" button behavior
### Summary

I can click the "Subscribe" button without entering any values in the required text fields for name and email. Submitting a blank form will still yield a confirmation page indicating you are subscribed.

Expected behavior:
1. Submit with blank required field(s)
3. In-line error message: `Enter a first name` and/or `Enter a valid email address`

[View states in Figma](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=8-27955&t=fQtYeWwWaSS9KPMK-4)

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

https://simpler.grants.gov/subscribe

> Leave form fields blank
> Click "Subscribe"
> View subscription confirmation screen

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by acouch**
## Summary
Fixes #3083

## Changes proposed
Fixes a bug, the nullish coalescing operator didn't work because the `errorMessage` value was never `null`, and didn't check for `validationErrors` properly which defaults to an empty object.

### Validate error
1. On `main`, go to `/subscribe`
2. Click "Subscribe" without entering any values
3. See you are redirected to `/subscribe/confirmation`

### Validate fix
1. On `acouch/issue-3083-fix-subscribe` go to `/subscribe`
2. Click "Subscribe" without entering any values
3. See: 
image
4. Enter a name only, see error:
image
5. Enter an email only, see error:
image
6. Enter all required fields
7. See you are redirected to `/subscribe/confirmation`

### CODE REVIEW

**Review by doug-s-nava — COMMENTED** [review]
change makes sense to me though I'm not sure exactly how to test it.

also, did you mean to commit the blank file?

**Comment by acouch** [comment]
> also, did you mean to commit the blank file?

No, removed.

**Comment by acouch** [comment]
> change makes sense to me though I'm not sure exactly how to test it.

We ran into trouble testing actual form actions with jest. I imagine this will be improved upstream at some point.

**Review by doug-s-nava — APPROVED** [review]
I'm unable to get the form to fully submit locally, but I assume that's a me problem, as this no longer allows me to submit without entering anything in the form.

**Pull request merged**
