### PR TITLE
[Issue 2552] opportunity detail heading updates

### LINKED ISSUE #2552: Opportunity page headings/content update
### Summary

Headings/content on the Opportunity page have been updated

Figma file: https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=239-2733&m=dev

### Changes:
- "Funding opportunity" section moved to the top of the left column
- "Description" changed to "Summary"
- added heading "Eligibility"
- "Eligible applicants" added as a subheading
- "Additional information on eligibility" changed to "Additional information"
- on summary.close_date_description change time format to remove commas > 5:00 p.m. ET
- move "Funding opportunity number" to the top of  list on the right column, below Award boxes

### Acceptance criteria

- [ ] "Funding opportunity" section moved to the top of the left column
- [ ] "Description" changed to "Summary"
- [ ] added heading "Eligibility"
- [ ] "Eligible applicants" added as a subheading
- [ ] "Additional information on eligibility" changed to "Additional information"
- [ ] on summary.close_date_description change time format to remove commas > 5:00 p.m. ET
- [ ] move "Funding opportunity number" to the top of  list on the right column, below Award boxes

### PR DESCRIPTION
**Pull request by doug-s-nava**
## Summary
Fixes #2552

## Changes proposed

- [x] "Funding opportunity" section moved to the top of the left column
- [x] "Description" changed to "Summary"
- [x] added heading "Eligibility"
- [x] "Eligible applicants" added as a subheading
- [x] "Additional information on eligibility" changed to "Additional information"
- [x] move "Funding opportunity number" to the top of  list on the right column, below Award boxes

### Test steps

1. load up an opportunity detail page
2. _VERIFY_ it matches largely with the figma file in terms of the items mentioned above

### Before

Screenshot 2024-10-25 at 11-40-51 Opportunity Listing - Research into Ecologist industry

### After

Screenshot 2024-10-25 at 11-40-28 Opportunity Listing - Research into Ecologist industry

### CODE REVIEW

**Review by emilycnava — COMMENTED** [review]
lgtm and verified changes locally, looks like e2e is failing

**Comment by doug-s-nava** [comment]
@crystabelrangel - I'd appreciate a quick look when you have time

**Review by acouch — APPROVED** [review]
LGTM!

**Comment by crystabelrangel** [comment]
Looks good!

**Pull request merged**
