### PR TITLE
[Issue #2231] Fix Checks failing on forked branches 

### LINKED ISSUE #2231: [Bug]: Error with jest test library for forked PRs
### Contact Details

emilycarlsen@navapbc.com

### What happened?

See slack thread: https://nava.slack.com/archives/C057K146W8H/p1727360663605829

Error:
ArtiomTr/jest-coverage-report-action@v2 - Error: Missing `checks: write` permission - Resource not available by integration

possible solution https://github.com/ArtiomTr/jest-coverage-report-action/issues/313#issuecomment-1416768086

### Steps to reproduce the behavior

Fork PR, create a new feature branch, make changes, push to your forked repo and then open a PR against HHS:main.

### Priority

medium (please fix soon)

### Relevant log output

_No response_

### Screenshots and additional context

Image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mdragon**
## Summary
Fixes #2231

## Changes proposed
While the coverage commenting back is what is breaking things, this is the only place the tests are run, so we don't want to just skip the whole action. We instead want it to run the tests, and just not do things that forks don't have permissions to do with the coverage reporting.

## Context for reviewers
Found this workaround/fix from the author on this ticket https://github.com/ArtiomTr/jest-coverage-report-action/issues/313#issuecomment-1238492603

### CODE REVIEW

**Comment by mdragon** [comment]
Should we set the labeler to not run in forks too?
image

https://github.com/HHS/simpler-grants-gov/actions/runs/11074308346/job/30772802371?pr=2241#step:2:9

**Comment by mdragon** [comment]
> Should we set the labeler to not run in forks too? image
> 
> https://github.com/HHS/simpler-grants-gov/actions/runs/11074308346/job/30772802371?pr=2241#step:2:9

@coilysiren you were too quick for me to get my philosophical question in.

**Comment by coilysiren** [comment]
@mdragon I'm not totally following how the pull request label relates to this PR?

**Comment by mdragon** [comment]
> @mdragon I'm not totally following how the pull request labeling relates to this PR?

I was trying to fix the front end tests Check failing when on a fork, but in doing so I was noticing the labeling Action also fails when on a fork.

**Comment by mdragon** [comment]
> Should we set the labeler to not run in forks too? image
> 
> https://github.com/HHS/simpler-grants-gov/actions/runs/11074308346/job/30772802371?pr=2241#step:2:9

@acouch think we're good to just not run the labeler if running in a fork?

**Comment by mdragon** [comment]
Update in fork

**Pull request closed without merging**
